/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteRouteImport } from './routes/dashboard/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PortalIndexRouteImport } from './routes/portal/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as DashboardTagihanIndexRouteImport } from './routes/dashboard/tagihan/index'
import { Route as DashboardTabunganIndexRouteImport } from './routes/dashboard/tabungan/index'
import { Route as DashboardSppIndexRouteImport } from './routes/dashboard/spp/index'
import { Route as DashboardSiswaIndexRouteImport } from './routes/dashboard/siswa/index'
import { Route as DashboardPengaturanIndexRouteImport } from './routes/dashboard/pengaturan/index'
import { Route as DashboardNotifikasiIndexRouteImport } from './routes/dashboard/notifikasi/index'
import { Route as DashboardLaporanIndexRouteImport } from './routes/dashboard/laporan/index'
import { Route as DashboardAuditIndexRouteImport } from './routes/dashboard/audit/index'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalIndexRoute = PortalIndexRouteImport.update({
  id: '/portal/',
  path: '/portal/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardTagihanIndexRoute = DashboardTagihanIndexRouteImport.update({
  id: '/tagihan/',
  path: '/tagihan/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardTabunganIndexRoute = DashboardTabunganIndexRouteImport.update({
  id: '/tabungan/',
  path: '/tabungan/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardSppIndexRoute = DashboardSppIndexRouteImport.update({
  id: '/spp/',
  path: '/spp/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardSiswaIndexRoute = DashboardSiswaIndexRouteImport.update({
  id: '/siswa/',
  path: '/siswa/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardPengaturanIndexRoute =
  DashboardPengaturanIndexRouteImport.update({
    id: '/pengaturan/',
    path: '/pengaturan/',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardNotifikasiIndexRoute =
  DashboardNotifikasiIndexRouteImport.update({
    id: '/notifikasi/',
    path: '/notifikasi/',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardLaporanIndexRoute = DashboardLaporanIndexRouteImport.update({
  id: '/laporan/',
  path: '/laporan/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardAuditIndexRoute = DashboardAuditIndexRouteImport.update({
  id: '/audit/',
  path: '/audit/',
  getParentRoute: () => DashboardRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/register': typeof RegisterRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/portal/': typeof PortalIndexRoute
  '/dashboard/audit/': typeof DashboardAuditIndexRoute
  '/dashboard/laporan/': typeof DashboardLaporanIndexRoute
  '/dashboard/notifikasi/': typeof DashboardNotifikasiIndexRoute
  '/dashboard/pengaturan/': typeof DashboardPengaturanIndexRoute
  '/dashboard/siswa/': typeof DashboardSiswaIndexRoute
  '/dashboard/spp/': typeof DashboardSppIndexRoute
  '/dashboard/tabungan/': typeof DashboardTabunganIndexRoute
  '/dashboard/tagihan/': typeof DashboardTagihanIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/register': typeof RegisterRoute
  '/dashboard': typeof DashboardIndexRoute
  '/portal': typeof PortalIndexRoute
  '/dashboard/audit': typeof DashboardAuditIndexRoute
  '/dashboard/laporan': typeof DashboardLaporanIndexRoute
  '/dashboard/notifikasi': typeof DashboardNotifikasiIndexRoute
  '/dashboard/pengaturan': typeof DashboardPengaturanIndexRoute
  '/dashboard/siswa': typeof DashboardSiswaIndexRoute
  '/dashboard/spp': typeof DashboardSppIndexRoute
  '/dashboard/tabungan': typeof DashboardTabunganIndexRoute
  '/dashboard/tagihan': typeof DashboardTagihanIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/register': typeof RegisterRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/portal/': typeof PortalIndexRoute
  '/dashboard/audit/': typeof DashboardAuditIndexRoute
  '/dashboard/laporan/': typeof DashboardLaporanIndexRoute
  '/dashboard/notifikasi/': typeof DashboardNotifikasiIndexRoute
  '/dashboard/pengaturan/': typeof DashboardPengaturanIndexRoute
  '/dashboard/siswa/': typeof DashboardSiswaIndexRoute
  '/dashboard/spp/': typeof DashboardSppIndexRoute
  '/dashboard/tabungan/': typeof DashboardTabunganIndexRoute
  '/dashboard/tagihan/': typeof DashboardTagihanIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/login'
    | '/onboarding'
    | '/register'
    | '/dashboard/'
    | '/portal/'
    | '/dashboard/audit/'
    | '/dashboard/laporan/'
    | '/dashboard/notifikasi/'
    | '/dashboard/pengaturan/'
    | '/dashboard/siswa/'
    | '/dashboard/spp/'
    | '/dashboard/tabungan/'
    | '/dashboard/tagihan/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/onboarding'
    | '/register'
    | '/dashboard'
    | '/portal'
    | '/dashboard/audit'
    | '/dashboard/laporan'
    | '/dashboard/notifikasi'
    | '/dashboard/pengaturan'
    | '/dashboard/siswa'
    | '/dashboard/spp'
    | '/dashboard/tabungan'
    | '/dashboard/tagihan'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/login'
    | '/onboarding'
    | '/register'
    | '/dashboard/'
    | '/portal/'
    | '/dashboard/audit/'
    | '/dashboard/laporan/'
    | '/dashboard/notifikasi/'
    | '/dashboard/pengaturan/'
    | '/dashboard/siswa/'
    | '/dashboard/spp/'
    | '/dashboard/tabungan/'
    | '/dashboard/tagihan/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  RegisterRoute: typeof RegisterRoute
  PortalIndexRoute: typeof PortalIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/': {
      id: '/portal/'
      path: '/portal'
      fullPath: '/portal/'
      preLoaderRoute: typeof PortalIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/tagihan/': {
      id: '/dashboard/tagihan/'
      path: '/tagihan'
      fullPath: '/dashboard/tagihan/'
      preLoaderRoute: typeof DashboardTagihanIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/tabungan/': {
      id: '/dashboard/tabungan/'
      path: '/tabungan'
      fullPath: '/dashboard/tabungan/'
      preLoaderRoute: typeof DashboardTabunganIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/spp/': {
      id: '/dashboard/spp/'
      path: '/spp'
      fullPath: '/dashboard/spp/'
      preLoaderRoute: typeof DashboardSppIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/siswa/': {
      id: '/dashboard/siswa/'
      path: '/siswa'
      fullPath: '/dashboard/siswa/'
      preLoaderRoute: typeof DashboardSiswaIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/pengaturan/': {
      id: '/dashboard/pengaturan/'
      path: '/pengaturan'
      fullPath: '/dashboard/pengaturan/'
      preLoaderRoute: typeof DashboardPengaturanIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/notifikasi/': {
      id: '/dashboard/notifikasi/'
      path: '/notifikasi'
      fullPath: '/dashboard/notifikasi/'
      preLoaderRoute: typeof DashboardNotifikasiIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/laporan/': {
      id: '/dashboard/laporan/'
      path: '/laporan'
      fullPath: '/dashboard/laporan/'
      preLoaderRoute: typeof DashboardLaporanIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/audit/': {
      id: '/dashboard/audit/'
      path: '/audit'
      fullPath: '/dashboard/audit/'
      preLoaderRoute: typeof DashboardAuditIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
  }
}

interface DashboardRouteRouteChildren {
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardAuditIndexRoute: typeof DashboardAuditIndexRoute
  DashboardLaporanIndexRoute: typeof DashboardLaporanIndexRoute
  DashboardNotifikasiIndexRoute: typeof DashboardNotifikasiIndexRoute
  DashboardPengaturanIndexRoute: typeof DashboardPengaturanIndexRoute
  DashboardSiswaIndexRoute: typeof DashboardSiswaIndexRoute
  DashboardSppIndexRoute: typeof DashboardSppIndexRoute
  DashboardTabunganIndexRoute: typeof DashboardTabunganIndexRoute
  DashboardTagihanIndexRoute: typeof DashboardTagihanIndexRoute
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardAuditIndexRoute: DashboardAuditIndexRoute,
  DashboardLaporanIndexRoute: DashboardLaporanIndexRoute,
  DashboardNotifikasiIndexRoute: DashboardNotifikasiIndexRoute,
  DashboardPengaturanIndexRoute: DashboardPengaturanIndexRoute,
  DashboardSiswaIndexRoute: DashboardSiswaIndexRoute,
  DashboardSppIndexRoute: DashboardSppIndexRoute,
  DashboardTabunganIndexRoute: DashboardTabunganIndexRoute,
  DashboardTagihanIndexRoute: DashboardTagihanIndexRoute,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  RegisterRoute: RegisterRoute,
  PortalIndexRoute: PortalIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
